// This file is part of www.nand2tetris.org
// and the book "The Elements of Computing Systems"
// by Nisan and Schocken, MIT Press.
// File name: projects/03/a/Bit.tst

load QuarterClock.hdl,
output-file QuarterClock.out,
// compare-to QuarterClock.cmp,
output-list time%S1.4.1 clockIn%B4.1.4 half%B2.1.2 quarter%B4.1.4;

output;
set clockIn 1,
tick, output; tock, output;
set clockIn 0,
tick, output; tock, output;
set clockIn 1,
tick, output; tock, output;
set clockIn 0,
tick, output; tock, output;
set clockIn 1,
tick, output; tock, output;
set clockIn 0,
tick, tock, output;
set clockIn 1,
tick, tock, output;
set clockIn 0,
tick, tock, output;
set clockIn 1,
tick, tock, output;
set clockIn 0,
tick, tock, output;
set clockIn 1,
tick, tock, output;
set clockIn 0,
tick, tock, output;
set clockIn 1,
tick, tock, output;
set clockIn 0,
tick, tock, output;
set clockIn 1,
tick, tock, output;
set clockIn 0,
tick, tock, output;

set clockIn 1,
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;

set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;

set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 1,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
set clockIn 0,
tick, tock, output;
tick, tock, output;
tick, tock, output;
tick, tock, output;
